### ISSUE TITLE
this is AMAZING :D

### ISSUE THREAD

**Issue by zeltak** [vifon/dired-rifle.el#1]
wow thx so much for this!!

ive been a ranger user 7 years ago almost and that was one of the things i missed the much in dired :D :D 

would you consider though adding the rifle config inside the emacs/dired conf? its somewhat weird for an emacs conf to relay on an external conf file :)..not a big issue though...

thx again!

Z

**Comment by vifon** [comment]
Good idea! I've just added a way to specify the path to your own rifle.conf.

I'm glad you like it!
