### ISSUE TITLE
how to use the rilfe ask option?

### ISSUE THREAD

**Issue by zeltak** [vifon/dired-rifle.el#2]
Hi again

sorry for the many issues, im just enjoying to use it alot :D 

so one of the things I remember back in the day using ranger was the `ask` option. this dosent seem to work in dired-ranger. could this work at all?

thx

Z

**Comment by vifon** [comment]
It seems rifle without ranger doesn't handle `ask` too nicely, essentially reporting that the file's type is unknown. You can emulate the `ask` behavior by pressing `C-u C-u r`. Is that acceptable for you?

**Comment by zeltak** [comment]
This is very useful :)
could there be an option ti use the C-u C-u r menu without leaving an empty dired buffer?
Also do you know of anyway to use rilfe to work on folder as opposed to a specific file?
my use case would be to quick launch a terminal app on dired folder using dired rifle which would be very cool indeed :)

thx again for your time and great work!

Z

**Comment by vifon** [comment]
> could there be an option ti use the C-u C-u r menu without leaving an empty dired buffer?

Not the menu, but you can use a numerical prefix argument to choose a non-default option (without the menu). I'll think about a way to add it. It's trivial in the code but I have trouble of thinking up a sensible way to invoke it UI-wise. If you have any ideas, speak up please. :)

> Also do you know of anyway to use rilfe to work on folder as opposed to a specific file?

I have this in my rifle.conf, that should help:

    directory, has rox, X, flag f = rox -- "$@"

**Comment by zeltak** [comment]
yeah thats awesome and worked well!! 
..but some more questions because of this :) (if its to much let me know :) )

1. this does not seem to work on all marked folder/files just the current one where point is. is that normal behavior? if I understand the ranger documentation the ``$@    | All selected files`` should work on all marked filed?

2. this dosent seem to work for launching stuff in the terminal. i tried this

```
directory, has terminator, X, flag t  = terminator -x beet import  -- "$@"
```

but that just quick flashes a terminal. any tips on how to launch selected folders/files in terminal/curses apps?

thx so much, i really appreciate all your help and effort. will be happy to help with testing with anything you need :)

best

Z

**Comment by vifon** [comment]
1. Yes, for now it works only on the current file. It may change in the future.

2. I just tried

       directory, has urxvt, X, flag t = urxvt -e vim "$@"

   And it works just fine, apart from the fact it makes no sense to use `flag t` and launch a terminal explicitly (that's literally what `flag t` does). Are you sure that terminator call is correct?

**Comment by zeltak** [comment]
haha yeah your right im an idiot with the `flag t`. :)

the urxvt command you posted works well and also my terminator command (with vim). I guess the issues i had is with CLI apps (like beet import) that run on a file and then exit. will need to figure out how to keep the term open :)

off topic a bit, i created this small function to quick access the 'ask' menu and bind it a key in emacs if anyone else is interested :) 

```
#+BEGIN_SRC emacs-lisp :results none
(defun z/dired-rifle-ask  ()
(interactive)                                
(let ((current-prefix-arg '(16)))             
(call-interactively #'dired-rifle)))
;(dired-rifle)))
#+END_SRC
```

best

Z
