### ISSUE TITLE
auto close the *dired-rifle* buffer?

### ISSUE THREAD

**Issue by zeltak** [vifon/dired-rifle.el#3]
Hi again
so i gotta give you again a HUGE thx for this package, this seriously is one of the best things to ever hit emacs for me (and ive been using emacs for 7 years... :))

If i can help in anyway (testing, writing documentation etc) let me know!!!

one small request  i would like (if you have time of course :)) is a way to either auto close the *dired-rifle* buffer (that keeps popping after the `C-u C-u r` method) or perhaps even allow a suppression of that buffer altogether

huge thx!!

Z

**Comment by vifon** [comment]
OK, you've convinced me. I'll make `C-u C-u r` discard the output and `C-u C-u C-u r` show it. Would it make sense to you?

**Comment by vifon** [comment]
I dropped the previous `C-u r` variant in 99547a330ee46db20da88308ef9a4c36e6ebb0cd, so what I described above became `C-u r` and `C-u C-u r` respectively.
